all:
  hosts:
    j-burg11-node-4:
      ansible_host: 192.168.1.186
      ip: 192.168.1.186
      ansible_user: hwestman
      ansible_ssh_private_key_file: <absolute/path/to/key>
    j-burg11-node-5:
      ansible_host: 192.168.1.189
      ip: 192.168.1.189
      ansible_user: hwestman
      ansible_ssh_private_key_file: <absolute/path/to/key>
    # j-burg11-node-6:
    #   ansible_host: 192.168.1.
    #   ip: 192.168.1.
    #   ansible_user: hwestman
    #   ansible_ssh_private_key_file: <absolute/path/to/key>
  children:
    kube-master:
      hosts:
        j-burg11-node-4:
        # j-burg11-node-5:
    kube-node:
      hosts:
        j-burg11-node-4:
        j-burg11-node-5:
        # j-burg11-node-6:
    etcd:
      hosts:
        j-burg11-node-4:
        # j-burg11-node-5:
        # j-burg11-node-6:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}